<?php $stylesheetDir = IMAGESERVE_DIR . "/assets/css/style.css"; ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php echo APP_NAME; ?></title>
        <link rel="stylesheet" href="<?php echo $stylesheetDir; ?>">
    </head>

    <body>
        <h1>You shouldnt be here, redirecting. (Edit /protected/templates/index.phtml to redirect to your own website or remove the redirect)</h1>
        <script> setTimeout(function(){ location.replace("https://example.com") }, 5000); </script>
    </body>
</html>
