<?php $stylesheetDir = IMAGESERVE_DIR . "/assets/css/style.css"; ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php echo APP_NAME; ?></title>
        <link rel="stylesheet" href="<?php echo $stylesheetDir; ?>">
    </head>

    <body>
        <h1>Tady nemáš co dělat, jdi na hlavní stránku >:( (Redirectuji)</h1>
        <script> setTimeout(function(){ location.replace("https://JustLeader.eu") }, 5000); </script>
    </body>
</html>
